#!/bin/bash
if [ $# = 3 ]
then
	find $(readlink -f "$2") -type f -user "$1" 1>"$3" 2>err_file -printf "%p %f %s\n"
	sed "s/find/`basename $0`/" err_file >&2
	rm err_file
	echo "total file amount:" $(wc -l < $3)
fi
